# Generated by Django 3.2 on 2021-05-20 15:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('emails', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='messages',
            options={'verbose_name': 'A. Check Emails', 'verbose_name_plural': 'A. Check Emails'},
        ),
        migrations.RenameField(
            model_name='messages',
            old_name='messages',
            new_name='message',
        ),
    ]
