# Generated by Django 3.2 on 2021-05-08 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pricing', '0003_auto_20210508_1443'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pricetable',
            options={'verbose_name': 'B. Pricing Table', 'verbose_name_plural': 'B. Pricing Table'},
        ),
        migrations.AlterField(
            model_name='pricetable',
            name='offer1',
            field=models.CharField(blank=True, default=0, max_length=150),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='pricetable',
            name='offer2',
            field=models.CharField(blank=True, default=0, max_length=150),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='pricetable',
            name='offer3',
            field=models.CharField(blank=True, default=0, max_length=150),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='pricetable',
            name='offer4',
            field=models.CharField(blank=True, default=0, max_length=150),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='pricetable',
            name='offer5',
            field=models.CharField(blank=True, default=0, max_length=150),
            preserve_default=False,
        ),
    ]
