# Generated by Django 3.2 on 2021-05-16 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='conthead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('headline', models.CharField(max_length=150)),
                ('title', models.CharField(max_length=150)),
                ('description', models.TextField(max_length=550)),
            ],
            options={
                'verbose_name': 'A. Headline, Title & Dscription',
                'verbose_name_plural': 'A. Headline, Title & Dscription',
            },
        ),
    ]
