# Generated by Django 3.2 on 2021-04-29 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='services',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('subtitle', models.CharField(max_length=150)),
            ],
            options={
                'verbose_name': 'A. Title & Subtitle',
                'verbose_name_plural': 'A. Title & Subtitle',
            },
        ),
    ]
