# Generated by Django 3.2 on 2021-04-29 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0003_auto_20210429_1505'),
    ]

    operations = [
        migrations.RenameField(
            model_name='items',
            old_name='link',
            new_name='description',
        ),
        migrations.RemoveField(
            model_name='items',
            name='subtitle',
        ),
        migrations.AddField(
            model_name='services',
            name='link',
            field=models.CharField(default=0, max_length=150),
            preserve_default=False,
        ),
    ]
