# Generated by Django 3.2 on 2021-04-29 09:24

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0005_remove_services_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='services',
            name='link',
            field=models.CharField(default=django.utils.timezone.now, max_length=150),
            preserve_default=False,
        ),
    ]
