# Generated by Django 3.2 on 2021-04-29 09:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0006_services_link'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='services',
            name='link',
        ),
    ]
