# Generated by Django 3.2 on 2021-04-29 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='about',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('headline', models.CharField(max_length=150)),
                ('description', models.TextField(max_length=300)),
                ('button', models.CharField(max_length=150)),
                ('link', models.CharField(max_length=150)),
                ('image', models.FileField(upload_to='profile/')),
            ],
            options={
                'verbose_name': 'A. Headline, Description & Image',
                'verbose_name_plural': 'A. Headline, Description & Image',
            },
        ),
    ]
