# Generated by Django 3.2 on 2021-05-08 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0002_auto_20210508_1151'),
    ]

    operations = [
        migrations.AlterField(
            model_name='items',
            name='description',
            field=models.TextField(max_length=150),
        ),
        migrations.AlterField(
            model_name='items',
            name='feature',
            field=models.FileField(upload_to='portfolio/'),
        ),
        migrations.AlterField(
            model_name='items',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='items',
            name='image',
            field=models.FileField(upload_to='portfolio'),
        ),
        migrations.AlterField(
            model_name='porthead',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
