# Generated by Django 3.2 on 2021-05-08 06:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0003_auto_20210508_1154'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='items',
            new_name='itemsb',
        ),
    ]
