# Generated by Django 3.2 on 2021-05-06 04:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('experience', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='education',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('year', models.CharField(max_length=150)),
                ('description', models.TextField(max_length=250)),
            ],
            options={
                'verbose_name': 'B. Add Education',
                'verbose_name_plural': 'B. Add Education',
            },
        ),
    ]
