# Generated by Django 3.2 on 2021-05-07 05:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('experience', '0003_exper'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='exper',
            new_name='workhis',
        ),
    ]
