# Generated by Django 3.2 on 2021-04-27 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Settings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('keywords', models.CharField(max_length=150)),
                ('description', models.TextField(max_length=150)),
                ('favicon', models.FileField(upload_to='favicon/')),
                ('previewImage', models.FileField(upload_to='preview/')),
            ],
        ),
    ]
