# Generated by Django 3.2 on 2021-04-27 05:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Content', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='settings',
            options={'verbose_name': 'A. Settings', 'verbose_name_plural': 'A. Settings'},
        ),
        migrations.RenameField(
            model_name='settings',
            old_name='previewImage',
            new_name='preview',
        ),
    ]
