# Generated by Django 3.2 on 2021-04-27 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Content', '0002_auto_20210427_1128'),
    ]

    operations = [
        migrations.AlterField(
            model_name='settings',
            name='favicon',
            field=models.ImageField(upload_to='favicon/'),
        ),
        migrations.AlterField(
            model_name='settings',
            name='preview',
            field=models.ImageField(upload_to='preview/'),
        ),
    ]
