# Generated by Django 3.2 on 2021-04-27 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Content', '0003_auto_20210427_1158'),
    ]

    operations = [
        migrations.CreateModel(
            name='Logo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('favicon', models.FileField(upload_to='logo/')),
            ],
            options={
                'verbose_name': 'A. Change Logo',
                'verbose_name_plural': 'A. Change Logo',
            },
        ),
        migrations.AlterField(
            model_name='settings',
            name='favicon',
            field=models.FileField(upload_to='favicon/'),
        ),
        migrations.AlterField(
            model_name='settings',
            name='preview',
            field=models.FileField(upload_to='preview/'),
        ),
    ]
