# Generated by Django 3.2 on 2021-06-17 11:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='basicpack',
            old_name='description',
            new_name='message',
        ),
        migrations.RenameField(
            model_name='basicpack',
            old_name='wanumber',
            new_name='number',
        ),
    ]
