# Generated by Django 3.2 on 2021-06-17 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_standardpack'),
    ]

    operations = [
        migrations.CreateModel(
            name='propack',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('email', models.CharField(max_length=150)),
                ('number', models.CharField(max_length=250)),
                ('message', models.TextField(max_length=750)),
            ],
            options={
                'verbose_name': 'C. Premium Pack',
                'verbose_name_plural': 'C. Premium Pack',
            },
        ),
    ]
