# Generated by Django 3.2 on 2021-04-28 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Settings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('headline', models.CharField(max_length=150)),
                ('title1', models.CharField(max_length=150)),
                ('title2', models.CharField(max_length=150)),
                ('title3', models.CharField(max_length=150)),
            ],
            options={
                'verbose_name': 'A. Headline and Titles',
                'verbose_name_plural': 'A. Headline and Titles',
            },
        ),
    ]
