# Generated by Django 3.2 on 2021-04-28 10:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('banner', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Settings',
            new_name='banner',
        ),
    ]
